apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ2aXNoYWxwYXRpbDAxMDUiLCJwYXNzd29yZCI6IlZhbG9yQDE2ODMjIyIsImVtYWlsIjoidmlzaGFscGF0aWwwMTA1QGdtYWlsLmNvbSIsImF1dGgiOiJkbWx6YUdGc2NHRjBhV3d3TVRBMU9sWmhiRzl5UURFMk9ETWpJdz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2024-12-04T15:41:01Z"
  name: docker-login-secrets
  namespace: default
  resourceVersion: "48081"
  uid: 6cd06b6c-6eab-4593-970c-fe905e6fdb63
type: kubernetes.io/dockerconfigjson